<a href="https://colab.research.google.com/github/J2yun/PyTorch/blob/master/Pytorch_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Gradient Descent**

In [0]:
import torch

1. Gradient Descent 활용

In [8]:
# Data
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[1], [2], [3]])

# Model 초기화
W = torch.zeros(1)
lr = 0.1

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    # H(x) 계산
    hypothesis = x_train * W

    # cost and gradient 계산
    cost = torch.mean((hypothesis - y_train) ** 2)
    gradient = torch.sum((W * x_train - y_train) * x_train)

    print('Epoch {:4d}/{} W: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), cost.item()))
    
    # gradient descent
    W -= lr*gradient

Epoch    0/10 W: 0.000 Cost: 4.666667
Epoch    1/10 W: 1.400 Cost: 0.746666
Epoch    2/10 W: 0.840 Cost: 0.119467
Epoch    3/10 W: 1.064 Cost: 0.019115
Epoch    4/10 W: 0.974 Cost: 0.003058
Epoch    5/10 W: 1.010 Cost: 0.000489
Epoch    6/10 W: 0.996 Cost: 0.000078
Epoch    7/10 W: 1.002 Cost: 0.000013
Epoch    8/10 W: 0.999 Cost: 0.000002
Epoch    9/10 W: 1.000 Cost: 0.000000
Epoch   10/10 W: 1.000 Cost: 0.000000


2. Optimizer 이용

In [0]:
import torch.optim as optim

In [16]:
# Model 초기화
W = torch.zeros(1, requires_grad = True)
optimizer = optim.SGD([W], lr=0.1)

nb_epochs = 10
for epoch in range(nb_epochs + 1):
    # H(x) 계산
    hypothesis = x_train * W

    # cost and gradient 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    print('Epoch {:4d}/{} W: {:.3f} Cost: {:.6f}'.format(
        epoch, nb_epochs, W.item(), cost.item()))
    
    optimizer.zero_grad() # gradient 0으로 초기화
    cost.backward() # gradient 계산 backward가 미분하는거 같음
    optimizer.step() # gradient descent

Epoch    0/10 W: 0.000 Cost: 4.666667
tensor([0.], requires_grad=True) tensor(4.6667, grad_fn=<MeanBackward0>)
Epoch    1/10 W: 0.933 Cost: 0.020741
tensor([0.9333], requires_grad=True) tensor(0.0207, grad_fn=<MeanBackward0>)
Epoch    2/10 W: 0.996 Cost: 0.000092
tensor([0.9956], requires_grad=True) tensor(9.2181e-05, grad_fn=<MeanBackward0>)
Epoch    3/10 W: 1.000 Cost: 0.000000
tensor([0.9997], requires_grad=True) tensor(4.0965e-07, grad_fn=<MeanBackward0>)
Epoch    4/10 W: 1.000 Cost: 0.000000
tensor([1.0000], requires_grad=True) tensor(1.8274e-09, grad_fn=<MeanBackward0>)
Epoch    5/10 W: 1.000 Cost: 0.000000
tensor([1.0000], requires_grad=True) tensor(7.7165e-12, grad_fn=<MeanBackward0>)
Epoch    6/10 W: 1.000 Cost: 0.000000
tensor([1.0000], requires_grad=True) tensor(9.9476e-14, grad_fn=<MeanBackward0>)
Epoch    7/10 W: 1.000 Cost: 0.000000
tensor([1.], requires_grad=True) tensor(0., grad_fn=<MeanBackward0>)
Epoch    8/10 W: 1.000 Cost: 0.000000
tensor([1.], requires_grad=True) t